import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { NavBar } from "@/components/ui/NavBar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar></NavBar>
        <main className="flex flex-col items-center justify-between p-24">
          {children}
        </main>
        <footer className="py-10 flex justify-center items-center">
          Proyecto final de Ciclo
        </footer>
      </body>
    </html>
  );
}
